version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    networks:
      - djangonetwork
    volumes:
      - .:/app

    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=afreetech
      - POSTGRES_PASSWORD=yvelos
      - POSTGRES_USER=jean
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '7082:5432'
    networks:
      - djangonetwork
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

networks:
  djangonetwork:
    driver: bridge

volumes:
  dbdata: