version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    volumes:
      - .:/app

    depends_on:
      - db

  db:
    container_name: vente_db
    image: postgres:14
    restart: always
    ports:
      - '7082:5432'
    env_file:
      - "admin/database.py"